# Topic ideas

---

Group name: Doreen Mack, David Riethmann

---

*Replace the italic texts with your descriptions*

In [2]:
import pandas as pd
df = pd.read_csv('../../Traffic_Crashes_-_Crashes_20231112.csv')

## Analysis Traffic Crashes Chicago

### Data source

    https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if


### Data characterisitcs

    Crash data shows information about each traffic crash on city streets within the City of Chicago limits and under the jurisdiction of Chicago Police Department (CPD).

    Updated: November 11, 2023
    Data Provided by: City of Chicago

    Size of the dataset fullfills the reqirements of the project. Data is on daily basis containing 49 columns with 779483 rows. 

    Multiple response variables available to choose from.

### Research question

#### Linear Regression

**Which aspects can help predict the number of units involved in a crash?**
- Y = number of units involved
- Column "NUM_UNITS", a unit can be a motor vehicle, a pedestrian, a bicyclist, or another non-passenger roadway user
- Possible predictor variables: Posted speed limit, traffic control device, weather condition, lighting condition, roadway surface condition, street alignment, work zone, injuries total, crash hour, crash day of week, crash month, crash location 

**Which aspects affect the number of injuries in a crash?**
- Y = Injuries total
- Column "INJURIES_TOTAL", total persons sustaining fatal, incapacitating, non-incapacitating, and possible injuries as determined by the reporting officer
- Possible predictor variables: Posted speed limit, traffic control device, weather condition, lighting condition, roadway surface condition, street alignment, work zone, injuries total, crash hour, number of units, road defect, trafficway type

#### Classification 

**Severity of the crash: Which aspects can help predict if an accident will result in injuries and/or require towing or if it will result in no injuries and the vehicles can drive away?**
- Column "CRASH_TYPE" can be either "Injury and/or Tow Due to Crash" or "No Injury / Drive Away"
- Possible predictor variables: Posted speed limit, weather condition, lighting condition, roadway surface condition, street alignment, road defect, work zone, trafficway type, damage

**Hit and Run: Which aspects can help predict whether a crash involved a hit and run, where a driver caused the crash and fled the scene without exchanging information and/or rendering aid?**
- Column "HIT_AND_RUN_I can be either yes or no and defines if the crash did/did not involve a driver who caused the crash and fled the scene without exchanging information and/or rendering aid
- Possible predictor variables: Posted speed limit, weather condition, lighting condition, roadway surface condition, street alignment, work zone, number of units involved, injuries total, crash hour, traffic control device

### Overview of data

    See below.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779483 entries, 0 to 779482
Data columns (total 49 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                779483 non-null  object
 1   RD_NO                          775008 non-null  object
 2   CRASH_DATE_EST_I               58551 non-null   object
 3   CRASH_DATE                     779483 non-null  object
 4   POSTED_SPEED_LIMIT             779483 non-null  int64
 5   TRAFFIC_CONTROL_DEVICE         779483 non-null  object
 6   DEVICE_CONDITION               779483 non-null  object
 7   WEATHER_CONDITION              779483 non-null  object
 8   LIGHTING_CONDITION             779483 non-null  object
 9   FIRST_CRASH_TYPE               779483 non-null  object
 10  TRAFFICWAY_TYPE                779483 non-null  object
 11  LANE_CNT                       199006 non-null  float64
 12  ALIGNMENT                      779483 non-null  object
 13  ROADWAY_SURFACE_COND           779483 non-null  object
 14  ROAD_DEFECT                    779483 non-null  object
 15  REPORT_TYPE                    756864 non-null  object
 16  CRASH_TYPE                     779483 non-null  object
 17  INTERSECTION_RELATED_I         178582 non-null  object
 18  NOT_RIGHT_OF_WAY_I             36079 non-null   object
 19  HIT_AND_RUN_I                  243452 non-null  object
 20  DAMAGE                         779483 non-null  object
 21  DATE_POLICE_NOTIFIED           779483 non-null  object
 22  PRIM_CONTRIBUTORY_CAUSE        779483 non-null  object
 23  SEC_CONTRIBUTORY_CAUSE         779483 non-null  object
 24  STREET_NO                      779483 non-null  int64
 25  STREET_DIRECTION               779479 non-null  object
 26  STREET_NAME                    779482 non-null  object
 27  BEAT_OF_OCCURRENCE             779478 non-null  float64
 28  PHOTOS_TAKEN_I                 10113 non-null   object
 29  STATEMENTS_TAKEN_I             17097 non-null   object
 30  DOORING_I                      2421 non-null    object
 31  WORK_ZONE_I                    4533 non-null    object
 32  WORK_ZONE_TYPE                 3527 non-null    object
 33  WORKERS_PRESENT_I              1159 non-null    object
 34  NUM_UNITS                      779483 non-null  int64
 35  MOST_SEVERE_INJURY             777768 non-null  object
 36  INJURIES_TOTAL                 777779 non-null  float64
 37  INJURIES_FATAL                 777779 non-null  float64
 38  INJURIES_INCAPACITATING        777779 non-null  float64
 39  INJURIES_NON_INCAPACITATING    777779 non-null  float64
 40  INJURIES_REPORTED_NOT_EVIDENT  777779 non-null  float64
 41  INJURIES_NO_INDICATION         777779 non-null  float64
 42  INJURIES_UNKNOWN               777779 non-null  float64
 43  CRASH_HOUR                     779483 non-null  int64
 44  CRASH_DAY_OF_WEEK              779483 non-null  int64
 45  CRASH_MONTH                    779483 non-null  int64
 46  LATITUDE                       774255 non-null  float64
 47  LONGITUDE                      774255 non-null  float64
 48  LOCATION                       774255 non-null  object
dtypes: float64(11), int64(6), object(32)
memory usage: 291.4+ MB

In [15]:
df.describe()

,POSTED_SPEED_LIMIT,LANE_CNT,STREET_NO,BEAT_OF_OCCURRENCE,NUM_UNITS,INJURIES_TOTAL,INJURIES_FATAL,INJURIES_INCAPACITATING,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE
count,779483.000000,1.990060e+05,779483.000000,779478.000000,779483.000000,777779.000000,777779.000000,777779.000000,777779.000000,777779.000000,777779.000000,777779.0,779483.000000,779483.000000,779483.000000,774255.000000,774255.000000
mean,28.397077,1.333032e+01,3686.006601,1242.627174,2.034790,0.188804,0.001192,0.020107,0.106736,0.060769,2.004753,0.0,13.205491,4.122719,6.699534,41.854826,-87.673531
std,6.191890,2.961623e+03,2888.303027,705.363446,0.452354,0.564575,0.037434,0.166101,0.421446,0.317176,1.159349,0.0,5.565238,1.979764,3.368798,0.333911,0.678372
min,0.000000,0.000000e+00,0.000000,111.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,0.000000,-87.936193
25%,30.000000,2.000000e+00,1245.000000,714.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,9.000000,2.000000,4.000000,41.782384,-87.721652
50%,30.000000,2.000000e+00,3200.000000,1211.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,14.000000,4.000000,7.000000,41.874708,-87.674053
75%,30.000000,4.000000e+00,5600.000000,1822.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,17.000000,6.000000,10.000000,41.924284,-87.633279
max,99.000000,1.191625e+06,451100.000000,6100.000000,18.000000,21.000000,4.000000,10.000000,21.000000,15.000000,61.000000,0.0,23.000000,7.000000,12.000000,42.022780,0.000000

In [9]:
df.head()

,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,6c1659069e9c6285a650e70d6f9b574ed5f64c12888479...,JG387648,NaN,08/18/2023 12:50:00 PM,15,OTHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,...,1.0,0.0,1.0,0.0,12,6,8,NaN,NaN,NaN
1,5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...,JG361138,NaN,07/29/2023 02:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,...,0.0,0.0,1.0,0.0,14,7,7,41.854120,-87.665902,POINT (-87.665902342962 41.854120262952)
2,61fcb8c1eb522a6469b460e2134df3d15f82e81fd93e9c...,JG388133,NaN,08/18/2023 05:58:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,...,1.0,0.0,1.0,0.0,17,6,8,41.942976,-87.761883,POINT (-87.761883496974 41.942975745006)
3,004cd14d0303a9163aad69a2d7f341b7da2a8572b2ab33...,JC524901,NaN,11/26/2019 08:38:00 AM,25,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDESTRIAN,...,0.0,0.0,1.0,0.0,8,3,11,NaN,NaN,NaN
4,a1d5f0ea90897745365a4cbb06cc60329a120d89753fac...,JG387475,NaN,08/18/2023 10:45:00 AM,20,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,...,0.0,0.0,1.0,0.0,10,6,8,NaN,NaN,NaN

In [4]:
df.tail()

,CRASH_RECORD_ID,RD_NO,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
779478,61c8dcd63fae60613bc9ec526fa901420cbe99a6d35840...,JG335280,NaN,07/10/2023 12:29:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,TURNING,...,0.0,0.0,2.0,0.0,12,2,7,41.857531,-87.644929,POINT (-87.644928607359 41.857530859236)
779479,89dc61af34d393db950397f0cc06d53b56d1f5e5fa14d4...,JG317141,NaN,06/26/2023 04:50:00 PM,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,4.0,0.0,16,2,6,41.746905,-87.644077,POINT (-87.644077151581 41.746904607442)
779480,3a5f25711e9162f0042a53337a25f2c3dc72893c1172d9...,JC519990,NaN,11/22/2019 07:30:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR TO FRONT,...,0.0,0.0,4.0,0.0,7,6,11,41.953655,-87.718926,POINT (-87.718925716094 41.953654536112)
779481,45d62ddd4e4b5572d253cc072b3927afc15489728f1ba8...,JG370579,NaN,08/05/2023 01:00:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING IMPROPERLY,RAIN,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,7,8,41.798505,-87.723459,POINT (-87.723458737142 41.798505044022)
779482,f2c0204e5392ff379e5804ad25fad66304949d517327c6...,JD403415,NaN,10/18/2020 12:03:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,...,0.0,0.0,4.0,0.0,0,1,10,41.776184,-87.703219,POINT (-87.703218946422 41.776183637489)

## Name of topic idea 2

### Data source

    https://data.montgomerycountymd.gov/Public-Safety/Crash-Reporting-Drivers-Data/mmzv-x632


### Data characterisitcs

    This dataset provides information on motor vehicle operators (drivers) involved in traffic collisions occurring on county and local roadways. The dataset reports details of all traffic collisions occurring on county and local roadways within Montgomery County, as collected via the Automated Crash Reporting System (ACRS) of the Maryland State Police, and reported by the Montgomery County Police, Gaithersburg Police, Rockville Police, or the Maryland-National Capital Park Police. This dataset shows each collision data recorded and the drivers involved.

    Updated: November 10, 2023
    Data Provided by: Montgomery County, MD

### Research question

    How does the age of the car affect the amount of crashes.

    How does the vehicle body type affect the amount of crashes.

#### Linear Regression

**Which aspects can help predict the age of vehicles involved in crashes?**
- Y = vehicle year
- Column "Vehicle Year", the vehicle's year --> age has to be calculated first
- Possible predictor variables: Vehicle damage extent, collision type, vehicle make, vehicle model, vehicle body type, equipment problems

**Which aspects can help predict the speed limit at a crash location?**
- Y = speed limit
- Column "Speed limit", local area posted speed limit
- Possible predictor variables: road type, weather conditions, lighting conditions, traffic control devices, vehicle movement

#### Classification

**Driver at fault:  Which aspects can help predict whether a driver is at fault in a given crash?**
- Column "Driver at fault", can be either yes or no
- Possible predictor variables: Collision type, driver substance abuse, driver distracted by, vehicle type, weather conditions, traffic control, vehicle movement, light, equipment problems, circumstance, vehicle body type

### Overview of data

    See below.

In [10]:
_df = pd.read_csv('../../Crash_Reporting_-_Drivers_Data_20231112.csv')

/tmp/ipykernel_933788/3221502297.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  _df = pd.read_csv('../../Crash_Reporting_-_Drivers_Data_20231112.csv')

In [11]:
_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168515 entries, 0 to 168514
Data columns (total 43 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Report Number                   168515 non-null  object
 1   Local Case Number               168515 non-null  object
 2   Agency Name                     168515 non-null  object
 3   ACRS Report Type                168515 non-null  object
 4   Crash Date/Time                 168515 non-null  object
 5   Route Type                      151898 non-null  object
 6   Road Name                       152884 non-null  object
 7   Cross-Street Type               151867 non-null  object
 8   Cross-Street Name               152873 non-null  object
 9   Off-Road Description            15629 non-null   object
 10  Municipality                    18551 non-null   object
 11  Related Non-Motorist            5338 non-null    object
 12  Collision Type                  167942 non-null  object
 13  Weather                         155421 non-null  object
 14  Surface Condition               148783 non-null  object
 15  Light                           167116 non-null  object
 16  Traffic Control                 143506 non-null  object
 17  Driver Substance Abuse          137825 non-null  object
 18  Non-Motorist Substance Abuse    4219 non-null    object
 19  Person ID                       168515 non-null  object
 20  Driver At Fault                 168515 non-null  object
 21  Injury Severity                 168515 non-null  object
 22  Circumstance                    30602 non-null   object
 23  Driver Distracted By            168515 non-null  object
 24  Drivers License State           158841 non-null  object
 25  Vehicle ID                      168515 non-null  object
 26  Vehicle Damage Extent           168210 non-null  object
 27  Vehicle First Impact Location   168359 non-null  object
 28  Vehicle Second Impact Location  168259 non-null  object
 29  Vehicle Body Type               165926 non-null  object
 30  Vehicle Movement                168141 non-null  object
 31  Vehicle Continuing Dir          165891 non-null  object
 32  Vehicle Going Dir               165891 non-null  object
 33  Speed Limit                     168515 non-null  int64
 34  Driverless Vehicle              168515 non-null  object
 35  Parked Vehicle                  168515 non-null  object
 36  Vehicle Year                    168515 non-null  int64
 37  Vehicle Make                    168491 non-null  object
 38  Vehicle Model                   168450 non-null  object
 39  Equipment Problems              134949 non-null  object
 40  Latitude                        168515 non-null  float64
 41  Longitude                       168515 non-null  float64
 42  Location                        168515 non-null  object
dtypes: float64(2), int64(2), object(39)
memory usage: 55.3+ MB

In [14]:
_df.describe()

         Speed Limit   Vehicle Year       Latitude      Longitude
count  168515.000000  168515.000000  168515.000000  168515.000000
mean       32.564312    1966.414432      39.083035     -77.112259
std        11.056977     340.454212       0.072106       0.098616
min         0.000000       0.000000      37.720000     -79.486000
25%        25.000000    2006.000000      39.024213     -77.189104
50%        35.000000    2011.000000      39.074843     -77.105148
75%        40.000000    2015.000000      39.139640     -77.039582
max        75.000000    9999.000000      39.990414     -75.527708

In [12]:
_df.head()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
0,MCP3040003N,190026050,Montgomery County Police,Property Damage Crash,05/31/2019 03:00:00 PM,NaN,NaN,NaN,NaN,PARKING LOT OF 3215 SPARTAN RD,...,15,No,No,2004,HONDA,TK,UNKNOWN,39.150044,-77.063089,"(39.15004368, -77.06308884)"
1,MCP1307000K,190024786,Montgomery County Police,Property Damage Crash,05/24/2019 05:00:00 PM,NaN,NaN,NaN,NaN,PARKING LOT,...,0,No,No,0,UNK,UNK,NaN,39.199047,-77.250743,"(39.19904667, -77.25074333)"
2,MCP2846008X,230034260,Montgomery County Police,Property Damage Crash,07/17/2023 10:45:00 AM,County,SELFRIDGE RD,County,RANDOLPH RD,NaN,...,35,No,No,2003,FORD,TK,NO MISUSE,39.054588,-77.085974,"(39.05458848, -77.08597423)"
3,MCP32610017,230034668,Montgomery County Police,Property Damage Crash,07/20/2023 11:40:00 PM,Maryland (State),MUNCASTER MILL RD,County,SHADY GROVE RD,NaN,...,45,No,No,2023,TOYT,CP,NO MISUSE,39.148721,-77.147111,"(39.14872076, -77.14711061)"
4,EJ78520081,230033429,Gaithersburg Police Depar,Property Damage Crash,07/13/2023 05:40:00 PM,Municipality,PERRY PKWY,Unknown,ENT TO SHOPPING CENTER,NaN,...,25,No,No,2001,KENWORTH,TRUCK,NaN,39.149085,-77.210731,"(39.14908542, -77.21073135)"

In [13]:
_df.tail()

,Report Number,Local Case Number,Agency Name,ACRS Report Type,Crash Date/Time,Route Type,Road Name,Cross-Street Type,Cross-Street Name,Off-Road Description,...,Speed Limit,Driverless Vehicle,Parked Vehicle,Vehicle Year,Vehicle Make,Vehicle Model,Equipment Problems,Latitude,Longitude,Location
168510,DM8338000C,16010228,Takoma Park Police Depart,Property Damage Crash,03/01/2016 10:01:00 AM,Municipality,NEW HAMPSHIRE SERVICE LA,Municipality,PRINCE GEORGES AVE,NaN,...,25,No,No,2016,FORD,EXPLORER,NO MISUSE,38.972560,-76.997466,"(38.97255976, -76.99746609)"
168511,MCP1182001S,170519976,Montgomery County Police,Property Damage Crash,07/19/2017 02:22:00 PM,County,CEDAR LA,Maryland (State),OLD GEORGETOWN RD,NaN,...,35,No,No,2008,NISSAN,ALTIMA,NO MISUSE,39.004640,-77.108502,"(39.00464, -77.10850167)"
168512,MCP1453008X,200046217,Montgomery County Police,Property Damage Crash,11/23/2020 07:37:00 AM,Maryland (State),RIDGE RD,Unknown,LITTLE SENECA PKWY,NaN,...,40,No,No,2008,CHEVROLET,EXPRESS,NO MISUSE,39.228963,-77.236757,"(39.22896333, -77.23675667)"
168513,MCP2568000M,190056701,Montgomery County Police,Property Damage Crash,11/23/2019 11:23:00 PM,County,SHADY GROVE RD,Ramp,RAMP 9 FR IS 370 EB TO SHADY GROVE RD,NaN,...,35,No,No,2018,FORD,TRANSIT VAN,NO MISUSE,39.120440,-77.180047,"(39.12043995, -77.18004738)"
168514,MCP1048000P,15003337,Montgomery County Police,Property Damage Crash,01/21/2015 09:02:00 AM,Maryland (State),FREDERICK RD,Municipality,W GUDE DR,NaN,...,35,No,No,2011,HONDA,CRV,NaN,39.106847,-77.158380,"(39.10684667, -77.15838)"